name: 'Bazel Pipeline'
steps:
  - id: 'build'
    name: ':bazel: Build'
    commands: './.buildkite/build.sh'

  - id: 'unit-test'
    name: ':bazel: Test'
    parallelism: 4
    commands: './.buildkite/test.sh'
